=== apache/openmeetings/WebContent/languages/language.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
  Licensed to the Apache Software Foundation (ASF) under one
  or more contributor license agreements.  See the NOTICE file
  distributed with this work for additional information
  regarding copyright ownership.  The ASF licenses this file
  to you under the Apache License, Version 2.0 (the
  "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at
  
      http://www.apache.org/licenses/LICENSE-2.0
    	  
  Unless required by applicable law or agreed to in writing,
  software distributed under the License is distributed on an
  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  KIND, either express or implied.  See the License for the
  specific language governing permissions and limitations
  under the License.
  
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="language">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="string">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="value"/>
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:integer"/>
      <xs:attribute name="name" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="value">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element ref="br" minOccurs="0" maxOccurs="unbounded" />
        <xs:element ref="i" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="br"/>
  <xs:element name="i" type="xs:string"/>
</xs:schema>

=== apache/openmeetings/WebContent/languages/bulgarian.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
  Licensed to the Apache Software Foundation (ASF) under one
  or more contributor license agreements.  See the NOTICE file
  distributed with this work for additional information
  regarding copyright ownership.  The ASF licenses this file
  to you under the Apache License, Version 2.0 (the
  "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at
  
      http://www.apache.org/licenses/LICENSE-2.0
    	  
  Unless required by applicable law or agreed to in writing,
  software distributed under the License is distributed on an
  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  KIND, either express or implied.  See the License for the
  specific language governing permissions and limitations
  under the License.
  


###############################################
This File is auto-generated by the LanguageEditor 
to add new Languages or modify/customize it use the LanguageEditor 
see http://openmeetings.apache.org/LanguageEditor.html for Details 
###############################################-->
<language xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:noNamespaceSchemaLocation="language.xsd">
  <string id="1" name="conference">
    <value>Конференция</value>
  </string>
  <string id="2" name="meeting">
    <value>Среща</value>
  </string>
  <string id="3" name="classroom">
    <value>Класна стая</value>
  </string>
  <string id="4" name="settings">
    <value>Настройки</value>
  </string>
  <string id="5" name="benutzer">
    <value>Профил</value>
  </string>
  <string id="6" name="admin">
    <value>Администриране</value>
  </string>
  <string id="7" name="stop">
    <value>Стоп</value>
  </string>
  <string id="8" name="record">
    <value>Запис</value>
  </string>
  <string id="9" name="nofile">
    <value>Няма наличен файл</value>
  </string>
  <string id="10" name="recordbyteacher">
    <value>Запис от учител</value>
  </string>
  <string id="11" name="connectedusers">
    <value>Свързани потребители</value>
  </string>
  <string id="12" name="startconf">
    <value>Започване на конференция</value>
  </string>
  <string id="13" name="myname">
    <value>Моето име</value>
  </string>
  <string id="14" name="videoconference">
    <value>Видеоконференция</value>
  </string>
  <string id="15" name="import">
    <value>Качване на файл</value>
  </string>
  <string id="16" name="refreshfiles">
    <value>Опресняване на списъка</value>
  </string>
  <string id="17" name="tomainfile">
    <value>Към главната папка</value>
  </string>
  <string id="18" name="newpoll">
    <value>Нова анкета</value>
  </string>
  <string id="19" name="newpollheader">
    <value>Нова анкета за конференцията.</value>
  </string>
  <string id="20" name="question">
    <value>Въпрос:</value>
  </string>
  <string id="21" name="polltype">
    <value>Тип анкета:</value>
  </string>
  <string id="22" name="create">
    <value>Създаване</value>
  </string>
  <string id="23" name="infomessage">
    <value>Инфо: Всеки свързан потребител получава съобщение за новата анкета.</value>
  </string>
  <string id="24" name="creatpoll">
    <value>Създаване на анкета</value>
  </string>
  <string id="25" name="cancel">
    <value>Отказ</value>
  </string>
  <string id="26" name="yesno">
    <value>Да/Не</value>
  </string>
  <string id="27" name="numeric">
    <value>Числов 1-10</value>
  </string>
  <string id="28" name="poll">
    <value>Анкета</value>
  </string>
  <string id="29" name="moderation">
    <value>Трябва да сте модератор, за да добавите нов въпрос</value>
  </string>
  <string id="30" name="vote">
    <value>Гласът Ви е отчетен.</value>
  </string>
  <string id="31" name="alreadyvoted">
    <value>Вече сте гласували в анкетата.</value>
  </string>
  <string id="32" name="voting">
    <value>Гласуване</value>
  </string>
  <string id="33" name="answer">
    <value>Вашият отговор:</value>
  </string>
  <string id="34" name="yes">
    <value>Да</value>
  </string>
  <string id="35" name="no">
    <value>Не</value>
  </string>
  <string id="36" name="questionwant">
    <value>иска да знае:</value>
  </string>
  <string id="37" name="pollresults">
    <value>Резултати от анкетата</value>
  </string>
  <string id="38" name="question">
    <value>Въпрос:</value>
  </string>
  <string id="39" name="results">
    <value>Резултати:</value>
  </string>
  <string id="40" name="answers">
    <value>Отговори:</value>
  </string>
  <string id="41" name="nopoll">
    <value>Не са започнати анкети.</value>
  </string>
  <string id="42" name="votings">
    <value>Гласуване</value>
  </string>
  <string id="43" name="meeting">
    <value>Среща (макс. 4 места)</value>
  </string>
  <string id="44" name="conference">
    <value>Конференция (макс. 50 места)</value>
  </string>
  <string id="45" name="type">
    <value>Тип</value>
  </string>
  <string id="46" name="remainingseats">
    <value>Оставащи места</value>
  </string>
  <string id="47" name="alreadychosen">
    <value>Вече избран</value>
  </string>
  <string id="48" name="enter">
    <value>вход</value>
  </string>
  <string id="49" name="modleave">
    <value>Модераторът е напуснал срещата.</value>
  </string>
  <string id="50" name="systemmessage">
    <value>Системна информация</value>
  </string>
  <string id="51" name="chossedevice">
    <value>Избор на устройства</value>
  </string>
  <string id="52" name="choosecam">
    <value>Избор на уебкамера:</value>
  </string>
  <string id="53" name="choosemic">
    <value>Избор на микрофон:</value>
  </string>
  <string id="54" name="ok">
    <value>ОК</value>
  </string>
  <string id="55" name="cancel2">
    <value>Отказ</value>
  </string>
  <string id="56" name="reconeectneeded">
    <value>Трябва да се свържете отново.</value>
  </string>
  <string id="57" name="editsetup">
    <value>Редактиране на настройките</value>
  </string>
  <string id="58" name="course">
    <value>Курс:</value>
  </string>
  <string id="59" name="language">
    <value>Език:</value>
  </string>
  <string id="60" name="ok2">
    <value>ОК</value>
  </string>
  <string id="61" name="cancel3">
    <value>Отказ</value>
  </string>
  <string id="62" name="clearwhiteboard">
    <value>Изчистване на дъската</value>
  </string>
  <string id="63" name="clearwhiteboardquestion">
    <value>Искате ли дъската да се изчиства, преди да бъде добавена нова снимка?</value>
  </string>
  <string id="64" name="dontaskagain">
    <value>Не питай отново</value>
  </string>
  <string id="65" name="no">
    <value>не</value>
  </string>
  <string id="66" name="editsetup2">
    <value>Редактиране на настройките</value>
  </string>
  <string id="67" name="needconfirmationwhiteboard">
    <value>Потвърждение преди изчистването на дъската</value>
  </string>
  <string id="68" name="userinfo">
    <value>Информация за потребител</value>
  </string>
  <string id="69" name="cleardrawarea">
    <value>Изчистване на зоната за рисуване</value>
  </string>
  <string id="70" name="undo">
    <value>Стъпка назад</value>
  </string>
  <string id="71" name="redo">
    <value>Стъпка напред</value>
  </string>
  <string id="72" name="selectobject">
    <value>Маркиране на обект</value>
  </string>
  <string id="73" name="text">
    <value>Текст</value>
  </string>
  <string id="74" name="paint">
    <value>Рисуване</value>
  </string>
  <string id="75" name="drawline">
    <value>Чертаене на линия</value>
  </string>
  <string id="76" name="drawu">
    <value>Подчертаване</value>
  </string>
  <string id="77" name="rect">
    <value>Правоъгълник</value>
  </string>
  <string id="78" name="ellipse">
    <value>Елипса</value>
  </string>
  <string id="79" name="arrow">
    <value>Стрелка</value>
  </string>
  <string id="80" name="deletechosen">
    <value>Изтриване на маркирания обект</value>
  </string>
  <string id="81" name="appliymod">
    <value>Искане на права на модератор</value>
  </string>
  <string id="82" name="apply">
    <value>Искане</value>
  </string>
  <string id="83" name="cancel">
    <value>Отказ</value>
  </string>
  <string id="84" name="mod">
    <value>Получаване на права на модератор</value>
  </string>
  <string id="85" name="close">
    <value>Затвори</value>
  </string>
  <string id="86" name="italic">
    <value>курсив</value>
  </string>
  <string id="87" name="bold">
    <value>получер</value>
  </string>
  <string id="88" name="waiting">
    <value>Изчакване...</value>
  </string>
  <string id="89" name="applyMessage">
    <value>Потребител иска права на модератор. Може да му дадете права само за рисуване върху дъската или напълно да му предадете правата на модератор.</value>
  </string>
  <string id="90" name="accept">
    <value>приемане</value>
  </string>
  <string id="91" name="reject">
    <value>отхвърляне</value>
  </string>
  <string id="92" name="cancel">
    <value>отказ</value>
  </string>
  <string id="93" name="sendmodrequestmessage">
    <value>Изпращане на молба към следните потребители</value>
  </string>
  <string id="94" name="accept">
    <value>Прието</value>
  </string>
  <string id="95" name="reject">
    <value>Отхвърлено</value>
  </string>
  <string id="96" name="changemod">
    <value>Смяна на модератор</value>
  </string>
  <string id="97" name="nonmoderrormessage">
    <value>Вие нямате права на модератор за този курс!</value>
  </string>
  <string id="98" name="moderator">
    <value>Модератор:</value>
  </string>
  <string id="99" name="roomfullmessage">
    <value>Стаята е пълна. Моля, опитайте отново по-късно.</value>
  </string>
  <string id="100" name="elllipse">
    <value>Елипса</value>
  </string>
  <string id="101" name="close">
    <value>затваряне</value>
  </string>
  <string id="102" name="AuthError">
    <value>грешка във входните данни</value>
  </string>
  <string id="103" name="min4username">
    <value>4 или повече знака; големите букви имат значение</value>
  </string>
